# App Info
ios_app_id                                : 1436647902                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : #https://www.reddit.com/r/deepfriedmemes                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").


app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The most popular meme deep fryer on the appstore!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Alex Barbulescu                                
your_link                                 : #https://alexs.ca                    
your_city                                 :                                
email_address                             : deepfriedapp@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : barbulescualex
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Frying
    description                           : This wouldn't be the most popular deep fryer on the appstore if you couldn't FRY. You can adjust brightness, saturation, contrast, pixellation and sharpness!
    fontawesome_icon_name                 : sliders-h
  
  - title                                 : Deep Fried Camera
    description                           : Take live Deep Fried pictures with the built in camera option!
    fontawesome_icon_name                 : camera
    
  - title                                 : Warping
    description                           : The Warp controller allows you to bump, pinch and swirl your memes to perfection!
    fontawesome_icon_name                 : fingerprint

  - title                                 : Text
    description                           : With the Edit controller you can add text customizing the size (with just a pinch or zoom), change the font and color!
    fontawesome_icon_name                 : heading

  - title                                 : Custom Assets
    description                           : You can add in your own image assets to use inside the Edit controller (PNGs included)!
    fontawesome_icon_name                 : image
  
  - title                                 : One Folder
    description                           : All of your masterpieces are saved into the 'Deep Fried Memes' folder!
    fontawesome_icon_name                 : folder
  
  - title                                 : Mozaic View
    description                           : All of the images inside your Deep Fried Memes folder are viewable and interactable from the app's home screen!
    fontawesome_icon_name                 : mobile




# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 1
topbar_title_color                        : "#ff0000"

cover_image                               : #assets/techHeader.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 1

device_color                              : black                                    # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#f8f8f8"

link_color                                : "#ff0000"

app_title_color                           : "#ff0000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#ff0000"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#ff0000"

footer_text_color                         : "#000000"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
